### ISSUE TITLE
Developer environment

### ISSUE THREAD

**Issue by rokoc003** [rokoc003/tidy_app#2]
# User Story
As a developer, I want to have a good environment to work with my project.

# Modules that are needed
- [ ] React: Create React App/ React-Router/  Prop-Types
- [ ] Design: Storybook/ emotion
- [ ] Backend: Express/ Node.js/ Nodemon/ MongoDB
- [ ] Prettier/ ESlint/ Husky
- [ ] Deployment

**Comment by marwinburesch** [comment]
Why do you want a good environment to work with your project? What does that have to do with storybook? 🙃
